### ISSUE TITLE
Translation pt-pt / br-pt

### ISSUE THREAD

**Issue by Inoque71** [yumi-modding/FS25_additionalFieldInfo#3]
Hello,
I added two translations pt-pt and br-pt
Regards
[modDesc.zip](https://github.com/user-attachments/files/17975573/modDesc.zip)

**Comment by yumi-modding** [comment]
Hello
Thanks I will add them to the next update

**Comment by yumi-modding** [comment]
Done with 0b3f2ec1563275382192b9bc8a7a604fd7084cfd
